name: CI Pipeline

on:
  push:
    branches:
      - main  # Run on push to main branch
  pull_request:
    branches:
      - main  # Run on PRs targeting main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'  # Caches dependencies

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          chmod +x test.sh

      - name: Run Tests
        run: ./test.sh

  deploy:
    name: Build and Deploy Package
    needs: test  # Runs only if tests pass
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          chmod +x build_package.sh

      - name: Build Package
        run: ./build_package.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-package
          path: dist/
          retention-days: 7  # Keep for 1 week
